name: Render figures

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - run: npm install -g @mermaid-js/mermaid-cli
      - run: sudo apt-get install -y graphviz
      - run: ./scripts/render-figures.sh
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: Render figures via CI
          add: figures
