name: Typos

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: typos-action
        uses: crate-ci/typos@v1.19.0
